#!/usr/bin/env python3

import os
import pathlib

path = pathlib.Path(__file__).parent.resolve()
os.chdir(path)

scripts = [
    ("daily problems", "pipenv run dailyproblems"),
    ("custom rank", "pipenv run customrank"),
    ("virtual performance", "pipenv run virtualperformance"),
    ("find unsolved contest problems", "pipenv run findunsolvedcontestproblems"),
    ("what if", "pipenv run whatif"),
]

print("Choose a script")
for i in range(len(scripts)):
    print("{}: {}".format(i + 1, scripts[i][0]))

choice = int(input())
assert(1 <= choice <= len(scripts))

choice -= 1

os.system(scripts[choice][1])
